name: Build
on:
  workflow_dispatch:
    inputs:
      onnxruntime-ref:
        type: string
        description: "ONNX Runtime repository reference, e.g., 'v1.22.2' or 'main'"
        default: "v1.23.1"
      target-preset:
        type: choice
        description: "Select a predefined target"
        required: false
        default: "static-x86_64-windows-msvc-mt"
        options:
          - "all"
          - dylib-aarch64-linux
          - static-aarch64-linux
          - dylib-x86_64-linux
          - static-x86_64-linux
          - dylib-aarch64-macos
          - static-aarch64-macos
          - dylib-x86_64-macos
          - static-x86_64-macos
          - dylib-x86_64-windows-msvc-md
          - static-x86_64-windows-msvc-md
          - dylib-x86_64-windows-msvc-mt
          - static-x86_64-windows-msvc-mt
          - wasm32-emscripten
          - dylib-aarch64-ios
          - static-aarch64-ios
          - dylib-aarch64-ios-simulator
          - static-aarch64-ios-simulator
          - dylib-aarch64-android
          - static-aarch64-android
      target-custom:
        type: string
        description: "Custom target filter (overrides preset if specified, supports substring matching)"
        required: false
      buildtype:
        type: choice
        required: true
        default: 'Both'
        options:
          - 'Both'
          - 'Release'
          - 'Debug'

env:
  # GCC_VERSION: '14.3'
  GCC_VERSION: '11'
  CMAKE_VERSION: '3.28'
  PYTHON_VERSION: '3.10'
  XCODE_VERSION: '14.3.1'

jobs:
  build-debug:
    if: inputs.buildtype == 'Both' || inputs.buildtype == 'Debug'
    uses: ./.github/workflows/_build-targets.yml
    with:
      onnxruntime-ref: ${{ inputs.onnxruntime-ref }}
      buildtype: Debug
      target-preset: ${{ inputs.target-preset }}
      target-custom: ${{ inputs.target-custom }}

  build-release:
    if: inputs.buildtype == 'Both' || inputs.buildtype == 'Release'
    uses: ./.github/workflows/_build-targets.yml
    with:
      onnxruntime-ref: ${{ inputs.onnxruntime-ref }}
      buildtype: Release
      target-preset: ${{ inputs.target-preset }}
      target-custom: ${{ inputs.target-custom }}
